# version: '3'

# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - redis
#     container_name: cache-middleware
#     image: cache-middleware:v20 

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"

version: '3'

services:
  redis:
    image: ahmadmukhtar7/redis:latest
    ports:
      - "6379:6379"

  node_app:
    build: .
    image: ahmadmukhtar7/cache-middleware:v20
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
